apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: comp_quizapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comp_quizapp
  template:
    metadata:
      labels:
        app: comp_quizapp
    spec:
      containers:
        - name: nginx
          image: newacrdemo.azurecr.io/comp_quizapp:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer-service
  labels:
    app: comp_quizapp
spec:
  type: LoadBalancer
  selector:
    app: comp_quizapp
  ports:
    - port: 80
      targetPort: 80
